### ISSUE TITLE
Well done!

### ISSUE THREAD

**Issue by benman1** [cemoktra/mlpp#6]
Hi Bastian!
I just want to say: that's a really cool project! Well done; I like the examples.

I also have a question though: is there any chance you could use a more commercially-friendly license such as MIT or CC BY-SA?

Cheers!
Ben

**Comment by cemoktra** [comment]
Hi. Thank you. Well I could. This was more of a learning project for me. Implementing everything myself for deeper understanding while doing python courses. I'm not actively working on it and don't think it's production ready.

**Comment by benman1** [comment]
That's ok, Bastian, no worries. I am guessing you've learned a lot from it. I think it is a very promising direction, though, that other people would want to contribute to as well. Don't give up on it. ;)

If you agree to license under the MIT license you could just drop another file like this here into your repo: https://github.com/julianschiavo/blog-example-code/blob/master/LICENSE

This would mean you double-license it (GPL + MIT). I am suggesting it, because it could give your project more traction.

**Comment by cemoktra** [comment]
Well the only difference is the patent use. And that's a thing I 
don't want to allow

**Comment by benman1** [comment]
Are you referring to the stipulations around patent litigation in the GPL3? Both MIT and CC-BY-SA are agnostic about patents. It's my understanding that the original author, would keep the copyright (regardless of the licence), and can file for patents (similar to GPL3).

I think licences can get in the way of getting things done, and integrating with other projects, that's why I was suggesting a change, however I don't want to get into a debate, and distract from what I came here to say that is that I like the project.

**Comment by cemoktra** [comment]
Thanks. Contribution is welcomed. Though I find few time for open source projects at the moment
